language: php

php:
- '7.2'

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

install:
- travis_retry composer install $COMPOSER_ARGS

script: php vendor/phpunit/phpunit/phpunit  --coverage-clover ./clover.xml

after_script:
- vendor/bin/php-coveralls -v
